spring:
  application:
    name: rikser-bundle

bundle:
  security:
    enabled: true
    service:
      enabled: true
      url: http://localhost:8081
  redis:
    enabled: true
    TTL: P1D
    prefix: prefix