spring:
  application:
    name: rikser-bundle

bundle:
  logging:
    masked-headers:
      - Authorization
    masked-properties:
      - password
  security:
    enabled: true
    service:
      enabled: true
      url: http://localhost:8081